version: 0.0
os: linux
files:
 - source: /index.html
   destination: /var/www/html/
hooks:
  Install:
    - location: scripts/setup.sh
      timeout: 3600
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 3600